name: "🌐 Other / Miscellaneous Issue"
description: "Create a new issue for topics not covered by existing templates."
title: "🌐 [MISC] - <title>"
labels:
  - "question"
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Please provide a detailed description of the issue or topic you'd like to discuss."
      placeholder: "Describe the issue, question, or topic in detail here..."
    validations:
      required: true

  - type: dropdown
    id: related_to
    attributes:
      label: "Related to"
      description: "Select the category this issue most closely relates to."
      options:
        - "Documentation"
        - "Code"
        - "UI/UX"
        - "Deployment"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: additional_information
    attributes:
      label: "Additional Information"
      description: "If there's any more info you'd like to provide, please do so here."
      placeholder: "Add any other details, links, or context..."
    validations:
      required: false
