name: Welcome

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Comment
        uses: actions/github-script@v5
        with:
          script: |
            const isIssue = context.payload.issue !== undefined;
            const item = isIssue ? context.payload.issue : context.payload.pull_request;
            const message = `Hello @${item.user.login}, thank you for your ${isIssue ? 'issue' : 'pull request'}! We appreciate your contribution.`;
            github.rest.issues.createComment({
              issue_number: item.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
