name: Welcome Issue

on:
  issues:
    types: [opened]

jobs:
  welcomeIssue:
    runs-on: ubuntu-latest
    steps:
      - name: Comment Issue
        uses: actions/github-script@v5
        with:
          script: |
            const { issue } = context;
            const message = `Hello @${issue.user.login}, thank you for raising this issue! We appreciate your input.`;
            github.rest.issues.createComment({
              issue_number: issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
